name: shawty
services:
  shawty:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: "shawty:latest"
    pull_policy: never
    build:
      context: ..
      dockerfile: "deploy/Dockerfile.service"
    ports:
      - "5001:80"
    volumes:
      - "../config:/app/config"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: "postgres:16"
    environment:
      POSTGRES_DB: shawty_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
       - "./data/postgres:/data/postgres"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
