services:
  atcc-service:
    container_name: atcc-service
    image: "atcc:latest"
    pull_policy: never
    build:
      context: ..
      dockerfile: "deploy/Dockerfile.service"
    ports:
      - "8080:80"
    volumes:
      - "../config:/app/config"
    restart: unless-stopped
    depends_on:
      atcc-postgres:
        condition: service_healthy

  atcc-postgres:
    container_name: atcc-postgres
    image: "postgres:16"
    environment:
      POSTGRES_DB: atcc_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
       - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
