domain: cc.alivetech.org
server:
  mode: debug
  host: 0.0.0.0
  port: 8010
log:
  level: debug
  encoding: json
  output_paths: ["stdout"]
  error_output_paths: ["stderr"]
  dev_mode: true
  encoder_config:
    message_key: message
    level_key: level
    level_encoder: lowercase
    time_key: timestamp
    time_encoder: iso8601
postgres:
  host: localhost
  port: 5432
  database: atcc_storage
  username: postgres
  password: postgres
