ssl: false
domain: "localhost:8010"
shared_secret: secret
jwt_secret: random_string
server:
  mode: debug
  host: 0.0.0.0
  port: 8010
log:
  level: debug
  encoding: json
  output_paths: ["stdout"]
  error_output_paths: ["stderr"]
  dev_mode: true
  encoder_config:
    message_key: message
    level_key: level
    level_encoder: lowercase
    time_key: timestamp
    time_encoder: iso8601
pagination:
  links_per_page: 20
postgres:
  host: localhost
  port: 5432
  database: shawty_storage
  username: postgres
  password: postgres
