name: format
on: [ pull_request ]

permissions:
  contents: read

jobs:
  goimports:
    name: Import checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: Setup goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Run checks
        run: goimports -d cmd internal

  gofumpt:
    name: General formatting checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: Setup gofumpt
        run: go install mvdan.cc/gofumpt@latest
      - name: Run checks
        run: gofumpt -d cmd internal

  golines:
    name: Line length checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: Setup golines
        run: go install github.com/segmentio/golines@latest
      - name: Run checks
        run: golines --dry-run -m 80 cmd internal
